/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Comp_1.h"
#include "Comp_2.h"
#include "Clock_1.h"
#include "CLK_1V5_aliases.h"
#include "CLK_1V5.h"
#include "DATA_1V5_aliases.h"
#include "DATA_1V5.h"
#include "ShiftReg_1.h"
#include "DATA_5V0_aliases.h"
#include "DATA_5V0.h"
#include "CLK_5V0_aliases.h"
#include "CLK_5V0.h"
#include "HighCheck50us.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "USBUART_1_cydmac.h"
#include "USBUART_1_msc.h"
#include "isr_1.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

